apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "bifrost-gateway-logs-*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.9.0"
    editable: true