# GitHub Actions Runner Configuration
# This file defines preferences for runner selection
#
# Strategy:
# - FJALL (Windows 11): Self-hosted runner for Windows builds
# - Linux/macOS: GitHub-hosted runners for consistency  
# - Python versions: Focus on 3.13+ (3.11/3.12 deprecated)
# - 15-second timeout for self-hosted availability

runner_preferences:
  # Primary runner preference
  primary: "self-hosted"
  
  # Fallback runners in order of preference
  fallback:
    - "ubuntu-latest"
    - "ubuntu-22.04"
  
  # Timeout settings
  timeouts:
    self_hosted_test: 15  # seconds to test self-hosted availability
    self_hosted_job: 1800  # 30 minutes max for self-hosted jobs
    cloud_fallback: 1200   # 20 minutes max for cloud fallback
  
  # Job-specific overrides
  jobs:
    # Windows builds use FJALL self-hosted runner
    build-windows:
      prefer_self_hosted: true
      require_self_hosted: false  # Fall back to cloud if unavailable
      reason: "Windows-specific testing on FJALL runner"
    
    # Linux/macOS builds use cloud runners
    build-linux:
      force_cloud: true
      reason: "Consistent cloud environment for Linux builds"
    
    build-macos:
      force_cloud: true
      reason: "Consistent cloud environment for macOS builds"
    
    # Python version testing uses cloud for consistency
    test-python-versions:
      force_cloud: true
      reason: "Consistent environment for version testing"

# Self-hosted runner labels
self_hosted_labels:
  - "self-hosted"
  - "FJALL"  # Your specific runner name
  - "windows"  # Windows host
  - "x64"

# Monitoring and alerts
monitoring:
  # Slack webhook for runner alerts (optional)
  slack_webhook_secret: "SLACK_WEBHOOK_URL"
  
  # Alert conditions
  alerts:
    - condition: "self_hosted_unavailable"
      message: "Self-hosted runner has been unavailable for >5 minutes"
    - condition: "repeated_fallbacks"
      message: "Using cloud fallback for >3 consecutive builds"