# Updated pyproject.toml for Google Python Style Guide compliance
# This shows the recommended changes to the existing configuration

[tool.ruff]
line-length = 80  # Changed from 88 to meet Google's requirement
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings  
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "D",    # pydocstyle (for docstring compliance)
    "PL",   # pylint rules
    "C90",  # mccabe complexity
    "N",    # pep8-naming
    "SIM",  # flake8-simplify
    "PTH",  # flake8-use-pathlib
    "RET",  # flake8-return
    "ARG",  # flake8-unused-arguments
]

ignore = [
    "E501",   # line too long (handled by formatter)
    "D100",   # Missing docstring in public module
    "D104",   # Missing docstring in public package
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the second line
    "PLR0913", # Too many arguments to function call
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",  # allow unused imports in __init__.py
    "D103",  # Missing docstring in public function
]
"tests/**/*.py" = [
    "B011",  # allow assert False in tests
    "D103",  # Missing docstring in public function
    "D102",  # Missing docstring in public method
    "D101",  # Missing docstring in public class
    "ARG001", # Unused function argument
    "ARG002", # Unused method argument
    "PLR2004", # Magic value used in comparison
]

[tool.ruff.lint.isort]
# Google Style Guide import organization
force-sort-within-sections = true
split-on-trailing-comma = true
combine-as-imports = true
known-first-party = ["bifrost", "bifrost_core"]
section-order = [
    "future",
    "standard-library", 
    "third-party",
    "first-party",
    "local-folder"
]

[tool.ruff.lint.pydocstyle]
# Enforce Google-style docstrings
convention = "google"

[tool.ruff.lint.mccabe]
# Maximum cyclomatic complexity (Google recommends keeping functions simple)
max-complexity = 10

[tool.ruff.lint.pylint]
# Additional pylint rules for Google compliance
max-args = 5
max-branches = 12
max-returns = 6
max-statements = 50

[tool.ruff.format]
# Google style formatting
line-ending = "auto"
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.mypy]
# Enhanced MyPy configuration for Google compliance
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
show_error_codes = true
show_column_numbers = true
pretty = true

# Additional rules for Google compliance
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true