[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bifrost-core"
version = "0.1.0"
description = "Core abstractions for Bifrost industrial IoT framework"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Bifrost Contributors", email = "hello@bifrost.dev"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: System :: Hardware",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.5",
    "typing-extensions>=4.8",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "mypy>=1.8",
    "ruff>=0.1.9",
]

[project.urls]
Documentation = "https://bifrost.readthedocs.io"
Repository = "https://github.com/bifrost-dev/bifrost"
Issues = "https://github.com/bifrost-dev/bifrost/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/bifrost_core"]

[tool.hatch.version]
path = "src/bifrost_core/__init__.py"