filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    fields:
      service: bifrost-gateway
      environment: production
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    multiline.pattern: '^\{'
    multiline.negate: true
    multiline.match: after

  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05.000-07:00'
      test:
        - '2023-01-01T00:00:00.000Z'

  - drop_fields:
      fields: ["beat", "offset", "input", "prospector"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "bifrost-gateway-logs-%{+yyyy.MM.dd}"
  template.name: "bifrost-gateway"
  template.pattern: "bifrost-gateway-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644