[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bifrost"
version = "0.1.0"
description = "Industrial IoT framework for bridging OT and IT systems"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Bifrost Contributors", email = "hello@bifrost.dev"}
]
keywords = ["industrial", "iot", "plc", "modbus", "automation", "scada"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License", 
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: System :: Hardware",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.13"
dependencies = [
    "bifrost-core>=0.1.0",
    "pymodbus>=3.5",
    "rich>=13.7",
    "typer>=0.12",
    "uvloop>=0.19",
    "orjson>=3.9",
]

[project.optional-dependencies]
opcua = ["bifrost-opcua>=0.1.0"]
analytics = ["bifrost-analytics>=0.1.0"] 
cloud = ["bifrost-cloud>=0.1.0"]
protocols = ["bifrost-protocols>=0.1.0"]
all = [
    "bifrost-opcua>=0.1.0",
    "bifrost-analytics>=0.1.0",
    "bifrost-cloud>=0.1.0", 
    "bifrost-protocols>=0.1.0",
]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "mypy>=1.8",
    "ruff>=0.1.9",
]

[project.scripts]
bifrost = "bifrost.cli:main"

[project.urls]
Documentation = "https://bifrost.readthedocs.io"
Repository = "https://github.com/bifrost-dev/bifrost"
Issues = "https://github.com/bifrost-dev/bifrost/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/bifrost"]

[tool.hatch.version]
path = "src/bifrost/__init__.py"