apiVersion: v1
kind: Namespace
metadata:
  name: bifrost-system
  labels:
    name: bifrost-system
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bifrost-resource-quota
  namespace: bifrost-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "10"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bifrost-network-policy
  namespace: bifrost-system
spec:
  podSelector:
    matchLabels:
      app: bifrost-gateway
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: bifrost-system
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 2112
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 502  # Modbus TCP
    - protocol: TCP
      port: 4840 # OPC UA