[package]
name = "bifrost-timeseries"
version = "0.1.0"
edition = "2021"
description = "High-performance time-series storage engine for Bifrost"
license = "MIT"
authors = ["Bifrost Contributors"]

[lib]
name = "bifrost_timeseries"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
thiserror = "1.0"
tracing = "0.1"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Compression
zstd = "0.13"

# Memory mapping
memmap2 = "0.9"

# Async support
tokio = { version = "1.0", features = ["full"], optional = true }

# Python bindings
pyo3 = { version = "0.22", features = ["extension-module"], optional = true }

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.0"

[features]
default = ["python-bindings"]
python-bindings = ["pyo3"]
async = ["tokio"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1