version: '3.8'

# Docker Compose configuration for edge device deployment
# Optimized for resource-constrained environments

services:
  bifrost-gateway:
    image: bifrost/gateway:latest
    container_name: bifrost-gateway-edge
    restart: unless-stopped
    ports:
      - "8080:8080"   # HTTP API
      - "9090:9090"   # gRPC
      - "2112:2112"   # Prometheus metrics
    volumes:
      - ./config/gateway.yaml:/config/gateway.yaml:ro
      - bifrost_logs:/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BIFROST_CONFIG_PATH=/config/gateway.yaml
      - BIFROST_LOG_LEVEL=info
      - BIFROST_EDGE_MODE=true
    networks:
      - bifrost-edge
    healthcheck:
      test: ["CMD", "/bifrost-gateway", "-health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "local"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  redis:
    image: redis:7-alpine
    container_name: bifrost-redis-edge
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - bifrost-edge
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'
        reservations:
          memory: 32M
          cpus: '0.1'

  # Lightweight monitoring stack for edge
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: bifrost-prometheus-edge
    restart: unless-stopped
    ports:
      - "9091:9090"  # Different port to avoid conflicts
    volumes:
      - ./monitoring/prometheus-edge.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'  # Shorter retention for edge
      - '--storage.tsdb.retention.size=1GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - bifrost-edge
    depends_on:
      - bifrost-gateway
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Optional: Lightweight metrics exporter
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: bifrost-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.meminfo'
      - '--collector.diskstats'
      - '--collector.filesystem'
      - '--collector.loadavg'
      - '--collector.netdev'
    networks:
      - bifrost-edge
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.1'
        reservations:
          memory: 16M
          cpus: '0.05'

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: bifrost-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Check every hour
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
    command: --interval 3600 --cleanup
    networks:
      - bifrost-edge
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.1'
        reservations:
          memory: 16M
          cpus: '0.05'

networks:
  bifrost-edge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  bifrost_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/prometheus