name: Dev Check

on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  quick-check:
    name: Quick Dev Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Set up Python
        run: uv python install 3.13
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Format check (auto-fixable)
        run: |
          echo "::group::Format issues (run 'just fmt' to fix)"
          uv run ruff format --check . || true
          echo "::endgroup::"
          
      - name: Lint check (auto-fixable)
        run: |
          echo "::group::Lint issues (run 'just lint' to fix)"
          uv run ruff check . || true
          echo "::endgroup::"
          
      - name: Quick test
        run: |
          echo "::group::Running quick tests"
          uv run pytest -xvs --tb=short packages/bifrost-core/tests || true
          echo "::endgroup::"
          
      - name: Summary
        if: always()
        run: |
          echo "## 📋 Dev Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Run these commands locally to fix issues:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "just fmt   # Auto-format code" >> $GITHUB_STEP_SUMMARY
          echo "just lint  # Fix linting issues" >> $GITHUB_STEP_SUMMARY
          echo "just test  # Run all tests" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY