name: Release

on:
  # Disabled for now - uncomment when ready for releases
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch: # Manual trigger only

permissions:
  contents: write
  actions: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Set up Python
        run: uv python install 3.13
        
      - name: Build packages
        run: |
          for pkg in packages/*/; do
            if [ -f "$pkg/pyproject.toml" ]; then
              echo "Building $pkg"
              (cd "$pkg" && uv build)
            fi
          done
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/*/dist/*.whl
            packages/*/dist/*.tar.gz
          generate_release_notes: true
          
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv pip install twine
          for pkg in packages/*/dist/*.whl; do
            if [ -f "$pkg" ]; then
              echo "Uploading $pkg to PyPI"
              uv run twine upload "$pkg" "${pkg%.whl}.tar.gz" --skip-existing
            fi
          done